<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RootNamespace>CleanArchitecture.Shared</RootNamespace>
    <AssemblyName>CleanArchitecture.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Requests\Yards\Bays\" />
    <Folder Include="Models\Requests\Yards\Blocks\" />
    <Folder Include="Models\Requests\Yards\Positions\" />
    <Folder Include="Models\Requests\Yards\Rows\" />
    <Folder Include="Models\Requests\Yards\Tiers\" />
    <Folder Include="Models\Responses\Yards\Bays\" />
    <Folder Include="Models\Responses\Yards\Blocks\" />
    <Folder Include="Models\Responses\Yards\Positions\" />
    <Folder Include="Models\Responses\Yards\Rows\" />
    <Folder Include="Models\Responses\Yards\Tiers\" />
  </ItemGroup>

</Project>
